# -*- coding: utf-8 -*-
"""python module 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2Y7Tx1MBEgWzkWOIwgrtL8dzlHhEODn

#problrm 1:Gaussian random number using box-muller
import random
import math
"""

#problem 1:
import random
import math

# Step 1: Generate two random numbers u and v between 0 and 1
u = random.random()
v = random.random()

# Step 2: Apply the Box-Muller formula
Z = math.sin(2 * math.pi * u) * math.sqrt(-2 * math.log(v))

# Step 3: Display results
print(f"u = {u:.6f}")
print(f"v = {v:.6f}")
print(f"Z = {Z:.6f}")

"""problem 2: Take 2 integers from command line and print in ascending order"""

#problem 2:
import sys

# Simulate command line: python p2.py 9 3
sys.argv = ['p2.py', '9', '3']   # ← change these numbers to test

a = int(sys.argv[1])
b = int(sys.argv[2])

if a <= b:
    print(a, b)
else:
    print(b, a)

"""problem 3: check if three numbers are strictly ascending or descending"""

#problem 3:
# Take three double values as input
x = float(input("Enter x: "))
y = float(input("Enter y: "))
z = float(input("Enter z: "))

# Check strictly ascending or strictly descending
if (x < y < z) or (x > y > z):
    print(True)
else:
    print(False)

"""problem 4:"""

# problem 4:
#Earthquake Magnitude Descriptor

magnitude = float(input("Enter earthquake magnitude: "))

if magnitude < 2.0:
    descriptor = "Micro"
elif magnitude < 3.0:
    descriptor = "Very Minor"
elif magnitude < 4.0:
    descriptor = "Minor"
elif magnitude < 5.0:
    descriptor = "Light"
elif magnitude < 6.0:
    descriptor = "Moderate"
elif magnitude < 7.0:
    descriptor = "Strong"
elif magnitude < 8.0:
    descriptor = "Major"
elif magnitude < 10.0:
    descriptor = "Great"
else:
    descriptor = "Meteoric"

print(f"A magnitude {magnitude} earthquake is considered to be a {descriptor} earthquake.")

"""problem 5:"""

#problem 5:
print(list(range(1, 22, 3)))

"""problem 6:"""

# Problem 6

s = 'I ate it.'

print(s.upper())        # makes everything uppercase
print(s.count('t'))     # counts how many times 't' appears
w = s.split()           # splits by spaces into a list
print(w)